USE ROLE SYSADMIN;
---------------------------------------------------------------------------------------

USE ROLE SECURITYADMIN;

CREATE ROLE "SF_DEVELOPER" COMMENT = 'ROLE TO HANDLE THE DATA IN SNOWFLAKE';
GRANT ROLE "SF_DEVELOPER" TO ROLE "SYSADMIN";

CREATE ROLE "DATA_LOADER" COMMENT = 'ROLE TO LOAD THE DATA INTO SNOWFLAKE';
GRANT ROLE "DATA_LOADER" TO ROLE "SF_DEVELOPER";

CREATE ROLE "DATA_UNLOADER" COMMENT = 'ROLE TO UNLOAD THE DATA FROM SNOWFLAKE';
GRANT ROLE "DATA_UNLOADER" TO ROLE "SF_DEVELOPER";

CREATE ROLE "DATA_ANALYST" COMMENT = 'ROLE FOR DATA ANALYST';
GRANT ROLE "DATA_ANALYST" TO ROLE "SYSADMIN";

CREATE ROLE "DATA_SCIENTIST" COMMENT = 'ROLE FOR DATA SCIENCE WORK';
GRANT ROLE "DATA_SCIENTIST" TO ROLE "SYSADMIN";

----------------------------------------------------------------------------------------
GRANT ROLE DATA_ANALYST TO USER "ADITI";
GRANT ROLE DATA_ANALYST TO USER "MAHENDRA";
GRANT ROLE DATA_ANALYST TO USER "SATISH";
GRANT ROLE DATA_ANALYST TO USER "PRADEEP";

GRANT ROLE DATA_SCIENTIST TO USER "SATYAJIT";

GRANT ROLE DATA_LOADER TO USER "ANANT";
GRANT ROLE DATA_LOADER TO USER "ANVESH";
GRANT ROLE DATA_LOADER TO USER "SHAKSHAM";
GRANT ROLE DATA_LOADER TO USER "OSAMA";

GRANT ROLE SF_DEVELOPER TO USER "YUKTHA";
GRANT ROLE SF_DEVELOPER TO USER "SATYAJIT";

GRANT ROLE SYSADMIN TO USER "YUKTHA";
GRANT ROLE SYSADMIN TO USER "SATYAJIT";



GRANT ROLE DATA_UNLOADER TO USER "YUKTHA";
GRANT ROLE DATA_UNLOADER TO USER "SATYAJIT";

GRANT ROLE SECURITYADMIN TO USER "YUKTHA";
