---------feeddback-------------
// Creating external stage

CREATE OR REPLACE STAGE PC_FIVETRAN_DB.PUBLIC.aws_stage
    url='s3://projectunity/feedback_data/'
    credentials=(aws_key_id='AKIAWPWG7LQZEHM53XU7' aws_secret_key='wR25209BeccmmOSozVqZaTdSQV+VFuKSPorw0XQS');
    
// Description of external stage

DESC STAGE PC_FIVETRAN_DB.PUBLIC.aws_stage;

//Table
use schema public;

create or replace table feedback (
  reviewerID varchar (100) , -- auto incrementing IDs   
  asin varchar (100),  -- variable string column
  reviewerName varchar (100), -- column used to store JSON type of data
  helpful string,
  reviewText string,
  overall float,
  summary varchar,
  unixReviewTime string,
  reviewTime string
);

COPY INTO feedback
    FROM @aws_stage
    file_format= PC_FIVETRAN_DB.public.feedback
    pattern='.*.csv*';
   

"PC_FIVETRAN_DB"."PUBLIC"."FEEDBACK"

-------------dataiku-----------------------
//creating LEAD table for Machine Learning
create or replace table lead 
clone pc_fivetran_db.fivetran_s3.lead;


use role pc_dataiku_role;
//create or replace view lead as  select * from pc_dataiku_db.public.lead;

----------------data transfer account-----------
//TABLE TRANSFER INTO DEVELOPMENT 


//Account_2 

CREATE OR REPLACE TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.ACCOUNT_2;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_2 CLUSTER BY (INDUSTRY,ACCOUNT_TYPE);

//Account_FEED 

CREATE OR REPLACE TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.ACCOUNT_FEED;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_FEED CLUSTER BY (DELETED,TITLE);


//ACCOUNT_HISTORY

CREATE OR REPLACE TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.ACCOUNT_HISTORY;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_HISTORY CLUSTER BY (DATE(CREATED_DATE));

//ACCOUNT_SHARE

CREATE OR REPLACE TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.ACCOUNT_SHARE;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE CLUSTER BY (ACCOUNT_ACCESS,CASE_ACCESS,DATE(LAST_MODIFIED_DATE),OPPORTUNITY_ACCESS);

// CHECKING NULL IN REVERSE_PARTNER_ID
SELECT COUNT(*) FROM (SELECT DISTINCT(REVERSE_PARTNER_ID) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE); // 30000 NULL VALUE 


// CHECKING NULL IN ROLE
SELECT COUNT(*) FROM (SELECT DISTINCT(ROLE) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN SYSTEM_MODSTAMP
SELECT COUNT(*) FROM (SELECT DISTINCT(SYSTEM_MODSTAMP) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN ACCOUNT_PARTNER_ID
SELECT COUNT(*) FROM (SELECT DISTINCT(ACCOUNT_PARTNER_ID) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN CREATED_BY_ID
SELECT COUNT(*) FROM (SELECT DISTINCT(CREATED_BY_ID) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN CREATED_DATE
SELECT COUNT(*) FROM (SELECT DISTINCT(CREATED_DATE) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN PRIMARY
SELECT COUNT(*) FROM (SELECT DISTINCT(PRIMARY) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);

// CHECKING NULL IN ACCOUNT_ID_1
SELECT COUNT(*) FROM (SELECT DISTINCT(ACCOUNT_ID_1) FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE);


//FILTERING DATA WITH CLEAR DATA
CREATE SECURE VIEW IF NOT EXISTS
DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE_VALID_VIEW_SECURE
AS (SELECT * FROM DEVELOPMENT.ACCOUNT.ACCOUNT_SHARE
   WHERE REVERSE_PARTNER_ID IS NOT NULL
   AND ACCOUNT_ID_1 IS NOT NULL
   AND PRIMARY IS NOT NULL
   AND CREATED_DATE IS NOT NULL
   AND CREATED_BY_ID IS NOT NULL
   AND ACCOUNT_PARTNER_ID IS NOT NULL);

----------------data transfer apex-----------------
//TABLE TRANSFER INTO DEVELOPMENT 


//APEX_PAGE 

CREATE OR REPLACE TABLE DEVELOPMENT.APEX.APEX_PAGE CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.APEX_PAGE;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE CLUSTER BY (API_VERSION,DATE(LAST_MODIFIED_DATE));

//APEX_PAGE_INFO 

CREATE OR REPLACE TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.APEX_PAGE_INFO;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.APEX.APEX_PAGE_INFO CLUSTER BY (STAR_RATING,DATE(LOG_DATE));


//APEX_TEST_RESULT 

CREATE OR REPLACE TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.APEX_TEST_RESULT;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.APEX.APEX_TEST_RESULT CLUSTER BY (PASS_FAIL);

//APEX_TEST_RESULT 

CREATE OR REPLACE TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB CLONE
PC_FIVETRAN_DB.FIVETRAN_S3.ASYNCAPEXJOB;

// REMOVING FIVETRAN GENERATED COLUMNS
ALTER TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB DROP COLUMN _FILE;
ALTER TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB DROP COLUMN _LINE;
ALTER TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB DROP COLUMN _MODIFIED;
ALTER TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB DROP COLUMN _FIVETRAN_SYNCED;

// CLUSTERING THE TABLE WITH MOST USED FIELDS
ALTER TABLE DEVELOPMENT.APEX.ASYNCAPEXJOB CLUSTER BY (JOB_TYPE,STATUS);
