USE ROLE SYSADMIN;
CREATE WAREHOUSE LOAD_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR DATALOADING';

USE ROLE SYSADMIN;
CREATE WAREHOUSE UNLOAD_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR DATA UNLOADING';

USE ROLE SYSADMIN;
CREATE WAREHOUSE BI_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR BI ACTIVITIES';

USE ROLE SYSADMIN;
CREATE WAREHOUSE DATA_ANALYSIS_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR DATA ANALYSIS';


USE ROLE SYSADMIN;
CREATE WAREHOUSE DATA_SCIENCE_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR DATA SCIENCE ACTIVITIES';

USE ROLE SYSADMIN;
CREATE WAREHOUSE SNOWFLAKE_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' 
COMMENT = 'WAREHOUSE FOR SNOWFLAKE ACTIVITIES';


-------------------------------------------------------------------------
GRANT modify, usage on warehouse unload_wh to role data_unloader;
grant modify, usage , monitor on warehouse unload_wh to role accountadmin;

similar to all warehouses
--------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "LOAD_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "LOAD_WH" SET RESOURCE_MONITOR = "LOAD_WH_MONITOR";



USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "UNLOAD_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "UNLOAD_WH" SET RESOURCE_MONITOR = "UNLOAD_WH_MONITOR";


USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "BI_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "BI_WH" SET RESOURCE_MONITOR = "BI_WH_MONITOR";


USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "DATA_ANALYSIS_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "DATA_ANALYSIS_WH" SET RESOURCE_MONITOR = "DATA_ANALYSIS_WH_MONITOR";

USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "DATA_SCIENCE_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "DATA_SCIENCE_WH" SET RESOURCE_MONITOR = "DATA_SCIENCE_WH_MONITOR";

USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR "SNOWFLAKE_WH_MONITOR" WITH CREDIT_QUOTA = 10 
 TRIGGERS 
 ON 90 PERCENT DO SUSPEND 
 ON 95 PERCENT DO SUSPEND_IMMEDIATE 
 ON 80 PERCENT DO NOTIFY;
ALTER WAREHOUSE "SNOWFLAKE_WH" SET RESOURCE_MONITOR = "SNOWFLAKE_WH_MONITOR";




